# NOT TO BE EDITED MANUALLY #
#############################

title = "TetOS internal metadata"



[source]

name.project    = "TetOS"
name.bootloader = "TetoEFI"
name.kernel     = "KasaneKernel"
version         = "00.50"


[repo]

author.real     = "Taylor"
author.first    = "Wakana"
author.last     = "Kisarazu"
copyright       = "2025-2026"

